import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
const inter = Inter({ subsets: ['latin'] });
import Header from '@/components/Header';
import { ClerkProvider } from '@clerk/nextjs';
import { ThemeProvider } from '@/components/ThemeProvider';
import toast, { Toaster } from 'react-hot-toast';
import Footer from '@/components/Footer';

export const metadata: Metadata = {
  title: 'Superdrive | Cloud Storage App',
  description: 'Generated by create next app',
    icons: {
    icon: '/favicon.ico',
    apple: '/apple-icon',
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
        <body className={inter.className}>
          <ClerkProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <Header />
              {children}
              <Footer />
              <Toaster />
            </ThemeProvider>
          </ClerkProvider>
        </body>
      </html>
  );
}
